# Generated by Django 3.2.8 on 2021-10-23 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(help_text='Enter your email address.', max_length=255, unique=True)),
                ('first_name', models.CharField(help_text='Enter your first name.', max_length=255)),
                ('last_name', models.CharField(help_text='Enter your Last or Surname only.', max_length=255)),
                ('other_names', models.CharField(blank=True, help_text='Enter your middle name(s).', max_length=255, null=True)),
                ('telephone', utility.validators.PossiblePhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telephone No.')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Enter middle or other names.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
