# Generated by Django 3.2.8 on 2021-10-23 14:09

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('residence', 'Residence'), ('work-place', 'Work-Place')], max_length=100, verbose_name='Residence or Work-Place')),
                ('apartment_house_no', models.CharField(max_length=100, verbose_name='House or Apt No.')),
                ('street_Address', models.CharField(max_length=100, verbose_name='Street Name and/or Number')),
                ('surburb', models.CharField(max_length=100, verbose_name='Surburb')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip', models.CharField(blank=True, help_text='Enter Your Residential GH-POST GPS or Zip Code', max_length=100, verbose_name='Zip')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
