# Generated by Django 3.2.8 on 2021-10-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='payload',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='operator',
        ),
        migrations.AddField(
            model_name='chat',
            name='communication',
            field=models.CharField(choices=[('sending', 'sending'), ('receiving', 'receiving')], default='receiving', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='conversation_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.conversationparty', to_field='uuid'),
        ),
    ]
