# Generated by Django 3.2.8 on 2021-10-23 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_chat_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Use right character in your message', regex='^[a-zA-Z0-9]{}$%_-\\/~@#$%^&*()!?')], verbose_name='Chat Payload'),
        ),
    ]
