# Generated by Django 3.2.8 on 2021-10-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_operatorchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorchat',
            old_name='sending_message',
            new_name='message',
        ),
    ]
