# Generated by Django 3.2.8 on 2021-10-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_discount_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationParty',
            new_name='Conversation',
        ),
    ]
