# Generated by Django 3.2.8 on 2021-10-25 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_conversationparty_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='chat',
            field=models.ForeignKey(default='5479f0b9-acb4-4b89-8ee6-4b7524286800', on_delete=django.db.models.deletion.CASCADE, to='store.operatorchat', to_field='uuid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='sending_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clientchat',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Please ensure that you use right characters in your message', regex='[\\*a-zA-Z0-9_\\{\\}\\$\\%\\_\\-\\\\\\/\\~\\@\\#\\$\\%\\^\\&\\*\\(\\)\\!\\?]*')], verbose_name='Chat Payload'),
        ),
        migrations.AlterField(
            model_name='operatorchat',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Please ensure that you use right characters in your message', regex='[\\*a-zA-Z0-9_\\{\\}\\$\\%\\_\\-\\\\\\/\\~\\@\\#\\$\\%\\^\\&\\*\\(\\)\\!\\?]*')], verbose_name='Chat Payload'),
        ),
    ]
