# Generated by Django 3.2.8 on 2021-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20211025_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
