# Generated by Django 3.2.8 on 2021-10-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_schedule_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sending_datetime',
            field=models.DateTimeField(default='2021-10-25 12:27:49.265626'),
            preserve_default=False,
        ),
    ]
