# Generated by Django 3.2.8 on 2021-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_schedule_sending_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('pending', 'pending')], default='pending', max_length=32),
        ),
    ]
