# Generated by Django 3.2.8 on 2021-10-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_schedule_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='operator',
            new_name='operator_uuid',
        ),
    ]
